[package]
name = "songrec"
license = "GPL-3.0+"
description = "An open-source Shazam client for Linux, written in Rust."
homepage = "https://github.com/marin-m/SongRec"
repository = "https://github.com/marin-m/SongRec"
readme = "README.md"
keywords = ["shazam", "audio", "audio-fingerprinting"]
categories = ["multimedia::audio", "command-line-utilities"]
version = "0.2.1"
authors = ["marin-m"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chfft = "0.3" # Fast Fourier transform
byteorder = "1.4" # Used for reading and writing binary structures
crc32fast = "1.3" # Used for the CRC-32 checksum in the binary signature
base64 = "0.21"
reqwest = { version = "0.11", features = ["json", "blocking", "rustls-tls"], default-features = false }

#reqwest = { version = "0.11", features = ["blocking", "json"] }
# rodio = "0.13.1" # For reading WAV/MP3/FLAG/OGG files, resampling and playing audio.
# clap = "2.33.2" # For argument parsing
# cpal = "0.13.3" # For recording audio
# gtk = { version = "0.9.2", features = ["v3_16", "v3_20", "v3_22"] } # For the GUI
# gdk = "0.13.2"
# gio = "0.9.1"
# hound = "3.4.0" # For writing WAV files
serde_json = "1.0" # For decoding and encoding JSON
uuid = { version = "1.4", features = ["v4"] }
# glib = "0.10.3"
percent-encoding = "2.3" # For percent-encoding contents in URLs
serde = { version = "1.0", features = ["derive"] }
# csv = "1.1.3"
# chrono = "0.4.13" # For formatting dates
# app_dirs = "1.2.1" # For obtaining and creating either the %APPDATA%, the dotfile path or similar
rand = "0.8"
# Note: gettext-rs and gettext-sys have been intentionnally downgraded:
# the latest versions don't link under Windows when cross-compiling using MinGW.
# gettext-sys = { version = "0.19.9", features = ["gettext-system"] }
# gettext-rs = { version = "0.5.0" }
# tempfile = "3.2.0"
# gdk-pixbuf = "0.9.0"

# [target.'cfg(target_os = "linux")'.dependencies]
# gag = "0.1.10" # Crate to silence stderr when CPAL produces uncontrolled AlsaLib output

